### ISSUE TITLE
"server closed connection"

### ISSUE THREAD

**Issue by sbbdms** [kobanium/aobazero#2]
Hi.
I am willing to contribute my hardware to this project, however i don't have a good network connection to the remote server... When I download the weight file, the speed is only 1MB/min.
Though the speed is slow, I can wait until it finishes downloading. However I find that the server always close and restart the connection every 10 minutes, and the weight file would never be downloaded with this period...
Any measure could help?
![reconnect](https://user-images.githubusercontent.com/19167292/57177174-2c5cb880-6e94-11e9-8182-e3d7be7fe0bf.png)

**Comment by yssaya** [comment]
Thank you for your contribution!
hmm.. We don't expect this slow speed.
We'll check server setting. please wait.

**Comment by yssaya** [comment]
We found some problems in autousi.
We will release ver 1.1 in a few days.
Thanks.

**Comment by sbbdms** [comment]
Thanks for your hard work...
I finally managed to download the network: Close the autousi manually after 8~9 minutes and restart, it will automatically detect the last file that has been downloaded and then download the next file.
However if I don't close the autousi manually, it will download from the 1st file (so, if I cannot download the whole weight file in 10 minutes, I would never finish downloading it).
I think this tactic is not proper so I am keeping this issue, until this tactic (or the server setting) is improved.

**Comment by yssaya** [comment]
We fixed a bug that autousi does not resume when the weight download fails midway.
Please try version 1.1.

**Comment by sbbdms** [comment]
It seems that the latest release makes sense. Thanks for your work!
